# Install NerdFont AND change it in the iterm2 or whatever you use!
format = '$python$all'


[python]
symbol = 'üêç '
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'


[aws]
symbol = "‚òÅÔ∏è "
format = '[$symbol($profile )(\($region\) )(\[$duration\] )]($style)' 
style = 'bold yellow'
force_display = true

[aws.profile_aliases]
default = 'default'


[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '


[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
up_to_date = '‚úì'

[nodejs]
format = '[$symbol($version )]($style)'
